#!/usr/bin/env bash
rm -rf env
python3 -m venv env
source env/bin/activate
pip install -U pip wheel setuptools
pip install click requests
pip install build
pip install flake8
pip freeze > requirements.txt
deactivate
